from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QAbstractItemView

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(680, 600)
        MainWindow.setMinimumSize(QtCore.QSize(680, 600))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelOriginalFiles = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelOriginalFiles.setFont(font)
        self.labelOriginalFiles.setObjectName("labelOriginalFiles")
        self.verticalLayout_2.addWidget(self.labelOriginalFiles)
        self.listWidgetFilesOld = QtWidgets.QListWidget(self.centralwidget)
        self.listWidgetFilesOld.setSelectionMode(QAbstractItemView.ExtendedSelection)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listWidgetFilesOld.setFont(font)
        self.listWidgetFilesOld.setObjectName("listWidgetFilesOld")
        self.verticalLayout_2.addWidget(self.listWidgetFilesOld)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem1 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem1)
        self.pushButtonMoveUp = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonMoveUp.sizePolicy().hasHeightForWidth())
        self.pushButtonMoveUp.setSizePolicy(sizePolicy)
        self.pushButtonMoveUp.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButtonMoveUp.setMaximumSize(QtCore.QSize(100, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonMoveUp.setFont(font)
        self.pushButtonMoveUp.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButtonMoveUp.setObjectName("pushButtonMoveUp")
        self.horizontalLayout_14.addWidget(self.pushButtonMoveUp)
        spacerItem2 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem2)
        self.pushButtonMoveDown = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonMoveDown.sizePolicy().hasHeightForWidth())
        self.pushButtonMoveDown.setSizePolicy(sizePolicy)
        self.pushButtonMoveDown.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButtonMoveDown.setMaximumSize(QtCore.QSize(100, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonMoveDown.setFont(font)
        self.pushButtonMoveDown.setObjectName("pushButtonMoveDown")
        self.horizontalLayout_14.addWidget(self.pushButtonMoveDown)
        spacerItem3 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15.addLayout(self.verticalLayout_6)
        spacerItem4 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem4)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.horizontalLayout_15.addWidget(self.line)
        spacerItem5 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelRenamedFiles = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelRenamedFiles.setFont(font)
        self.labelRenamedFiles.setObjectName("labelRenamedFiles")
        self.verticalLayout_3.addWidget(self.labelRenamedFiles)
        self.listWidgetFilesNew = QtWidgets.QListWidget(self.centralwidget)
        self.listWidgetFilesNew.setSelectionMode(QAbstractItemView.ExtendedSelection)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listWidgetFilesNew.setFont(font)
        self.listWidgetFilesNew.setObjectName("listWidgetFilesNew")
        self.verticalLayout_3.addWidget(self.listWidgetFilesNew)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        spacerItem6 = QtWidgets.QSpacerItem(40, 35, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem6)
        self.horizontalLayout_15.addLayout(self.verticalLayout_4)
        spacerItem7 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem7)
        self.verticalLayout_7.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem8 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem8)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tabSequentially = QtWidgets.QWidget()
        self.tabSequentially.setObjectName("tabSequentially")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tabSequentially)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem9 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem9)
        self.labelStandardName = QtWidgets.QLabel(self.tabSequentially)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelStandardName.sizePolicy().hasHeightForWidth())
        self.labelStandardName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelStandardName.setFont(font)
        self.labelStandardName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelStandardName.setObjectName("labelStandardName")
        self.horizontalLayout_13.addWidget(self.labelStandardName)
        spacerItem10 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem10)
        self.lineEditStandardName = QtWidgets.QLineEdit(self.tabSequentially)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditStandardName.setFont(font)
        self.lineEditStandardName.setObjectName("lineEditStandardName")
        self.horizontalLayout_13.addWidget(self.lineEditStandardName)
        spacerItem11 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem11)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBoxNumStyle = QtWidgets.QGroupBox(self.tabSequentially)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxNumStyle.sizePolicy().hasHeightForWidth())
        self.groupBoxNumStyle.setSizePolicy(sizePolicy)
        self.groupBoxNumStyle.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBoxNumStyle.setFont(font)
        self.groupBoxNumStyle.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBoxNumStyle.setObjectName("groupBoxNumStyle")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBoxNumStyle)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem12)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButtonDot = QtWidgets.QRadioButton(self.groupBoxNumStyle)
        self.radioButtonDot.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButtonDot.setAutoFillBackground(False)
        self.radioButtonDot.setObjectName("radioButtonDot")
        self.horizontalLayout.addWidget(self.radioButtonDot)
        spacerItem13 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem13)
        self.radioButtonDash = QtWidgets.QRadioButton(self.groupBoxNumStyle)
        self.radioButtonDash.setObjectName("radioButtonDash")
        self.horizontalLayout.addWidget(self.radioButtonDash)
        spacerItem14 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem14)
        self.radioButtonUnderline = QtWidgets.QRadioButton(self.groupBoxNumStyle)
        self.radioButtonUnderline.setObjectName("radioButtonUnderline")
        self.horizontalLayout.addWidget(self.radioButtonUnderline)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem15)
        self.horizontalLayout_5.addWidget(self.groupBoxNumStyle)
        self.groupBoxStartCount = QtWidgets.QGroupBox(self.tabSequentially)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxStartCount.sizePolicy().hasHeightForWidth())
        self.groupBoxStartCount.setSizePolicy(sizePolicy)
        self.groupBoxStartCount.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBoxStartCount.setFont(font)
        self.groupBoxStartCount.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBoxStartCount.setObjectName("groupBoxStartCount")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBoxStartCount)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem16)
        self.lineEditStartingPoint = QtWidgets.QLineEdit(self.groupBoxStartCount)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditStartingPoint.sizePolicy().hasHeightForWidth())
        self.lineEditStartingPoint.setSizePolicy(sizePolicy)
        self.lineEditStartingPoint.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditStartingPoint.setFont(font)
        self.lineEditStartingPoint.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditStartingPoint.setObjectName("lineEditStartingPoint")
        self.lineEditStartingPoint.setText('1')
        self.horizontalLayout_3.addWidget(self.lineEditStartingPoint)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem17)
        self.horizontalLayout_5.addWidget(self.groupBoxStartCount)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.tabSequentially, "")
        self.tabReplace = QtWidgets.QWidget()
        self.tabReplace.setObjectName("tabReplace")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.tabReplace)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem18 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem18)
        self.labelReplace = QtWidgets.QLabel(self.tabReplace)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelReplace.sizePolicy().hasHeightForWidth())
        self.labelReplace.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelReplace.setFont(font)
        self.labelReplace.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelReplace.setObjectName("labelReplace")
        self.horizontalLayout_7.addWidget(self.labelReplace)
        spacerItem19 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem19)
        self.lineEditReplaced = QtWidgets.QLineEdit(self.tabReplace)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditReplaced.setFont(font)
        self.lineEditReplaced.setObjectName("lineEditReplaced")
        self.horizontalLayout_7.addWidget(self.lineEditReplaced)
        spacerItem20 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem20)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem21 = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem21)
        self.labelInsert = QtWidgets.QLabel(self.tabReplace)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelInsert.sizePolicy().hasHeightForWidth())
        self.labelInsert.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelInsert.setFont(font)
        self.labelInsert.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelInsert.setObjectName("labelInsert")
        self.horizontalLayout_8.addWidget(self.labelInsert)
        spacerItem22 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem22)
        self.lineEditInserted = QtWidgets.QLineEdit(self.tabReplace)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditInserted.setFont(font)
        self.lineEditInserted.setObjectName("lineEditInserted")
        self.horizontalLayout_8.addWidget(self.lineEditInserted)
        spacerItem23 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem23)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tabReplace, "")
        self.tabRemove = QtWidgets.QWidget()
        self.tabRemove.setObjectName("tabRemove")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.tabRemove)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem24 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem24)
        self.labelRemove = QtWidgets.QLabel(self.tabRemove)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelRemove.setFont(font)
        self.labelRemove.setObjectName("labelRemove")
        self.horizontalLayout_10.addWidget(self.labelRemove)
        spacerItem25 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem25)
        self.lineEditRemove = QtWidgets.QLineEdit(self.tabRemove)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditRemove.setFont(font)
        self.lineEditRemove.setObjectName("lineEditRemove")
        self.horizontalLayout_10.addWidget(self.lineEditRemove)
        spacerItem26 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem26)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_10)
        self.tabWidget.addTab(self.tabRemove, "")
        self.horizontalLayout_12.addWidget(self.tabWidget)
        spacerItem27 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem27)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem28 = QtWidgets.QSpacerItem(10, 15, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem28)
        self.pushButtonApply = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonApply.setFont(font)
        self.pushButtonApply.setObjectName("pushButtonApply")
        self.horizontalLayout_4.addWidget(self.pushButtonApply)
        spacerItem29 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem29)
        self.pushButtonSave = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonSave.setFont(font)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.horizontalLayout_4.addWidget(self.pushButtonSave)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem30)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 680, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuLanguage = QtWidgets.QMenu(self.menuOptions)
        self.menuLanguage.setObjectName("menuLanguage")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen_files = QtWidgets.QAction(MainWindow)
        self.actionOpen_files.setObjectName("actionOpen_files")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionEnglish = QtWidgets.QAction(MainWindow)
        self.actionEnglish.setObjectName("actionEnglish")
        self.actionPortugu_s_Brasil = QtWidgets.QAction(MainWindow)
        self.actionPortugu_s_Brasil.setObjectName("actionPortugu_s_Brasil")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionOpen_files)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExit)
        self.menuLanguage.addAction(self.actionEnglish)
        self.menuLanguage.addAction(self.actionPortugu_s_Brasil)
        self.menuOptions.addAction(self.menuLanguage.menuAction())
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "-"))
        self.labelOriginalFiles.setText(_translate("MainWindow", "-"))
        self.pushButtonMoveUp.setText(_translate("MainWindow", "-"))
        self.pushButtonMoveDown.setText(_translate("MainWindow", "-"))
        self.labelRenamedFiles.setText(_translate("MainWindow", "-"))
        self.labelStandardName.setText(_translate("MainWindow", "-"))
        self.groupBoxNumStyle.setTitle(_translate("MainWindow", "-"))
        self.radioButtonDot.setText(_translate("MainWindow", ".001"))
        self.radioButtonDash.setText(_translate("MainWindow", "- 001"))
        self.radioButtonUnderline.setText(_translate("MainWindow", "_001"))
        self.groupBoxStartCount.setTitle(_translate("MainWindow", "-"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSequentially), _translate("MainWindow", "-"))
        self.labelReplace.setText(_translate("MainWindow", "-"))
        self.labelInsert.setText(_translate("MainWindow", "-"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabReplace), _translate("MainWindow", "-"))
        self.labelRemove.setText(_translate("MainWindow", "-"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRemove), _translate("MainWindow", "-"))
        self.pushButtonApply.setText(_translate("MainWindow", "-"))
        self.pushButtonSave.setText(_translate("MainWindow", "-"))
        self.menuFile.setTitle(_translate("MainWindow", "-"))
        self.menuOptions.setTitle(_translate("MainWindow", "-"))
        self.menuLanguage.setTitle(_translate("MainWindow", "-"))
        self.menuHelp.setTitle(_translate("MainWindow", "-"))
        self.actionOpen_files.setText(_translate("MainWindow", "-"))
        self.actionOpen_files.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "-"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExit.setText(_translate("MainWindow", "-"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionEnglish.setText(_translate("MainWindow", "English"))
        self.actionPortugu_s_Brasil.setText(_translate("MainWindow", "Português Brasil"))
        self.actionAbout.setText(_translate("MainWindow", "-"))
        self.actionAbout.setShortcut(_translate("MainWindow", "Ctrl+A"))
